FROM ollama/ollama:latest

# Copia o script para o diretório de trabalho
COPY ./run-ollama.sh /app/run-ollama.sh

# Define o diretório de trabalho
WORKDIR /app

# Torna o script executável
RUN chmod +x run-ollama.sh

